// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqhmhsmufgcoiajgxzmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxaG1oc211Zmdjb2lhamd4em1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0OTk0ODgsImV4cCI6MjA2MjA3NTQ4OH0.O2Hie0CjHdpJEvEFyRzaSXuq36ul3HvGegCSIJoQiDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);